//--------------------------------------------------------------
// rAthena Battle Configuration File
// Originally Translated by Peter Kieser <pfak@telus.net>
// Made in to plainer English by Ancyker
// Splitted up into multiple files by Skotlex.
//--------------------------------------------------------------
//=====================================
// Max resistance capping configuration
// 100 = max resistance is 100%
//=====================================
max_ele_def: 99
max_size_def: 99
max_race2_def: 99
max_race_def: 99
max_class_def: 99
max_short_def: 99
max_long_def: 99