// --------------------------------------------------------------
// -                       Custom Scripts                       -
// --------------------------------------------------------------
//      All the custom scripts, remove the '//' to enable...     
//      Place your scripts here!

// ----------------------- Basic Scripts -----------------------
//npc: npc/re/npcjuti-c4/basic/jobmaster.txt
//npc: npc/re/npcjuti-c4/basic/Scripts_City_Buffs.txt
//npc: npc/re/npcjuti-c4/basic/Scripts_City_KafraServices.txt
//npc: npc/re/npcjuti-c4/basic/warper.txt
